/**
 * Articles de blog SEO — français uniquement, contenu statique.
 * URL : /fr/blog et /fr/blog/<slug>
 *
 * ⚠️ Ne jamais publier la grille tarifaire interne (coefficients,
 * majorations régionales) : uniquement des fourchettes indicatives.
 */

export type BlogBlock =
  | { type: 'h2'; text: string }
  | { type: 'p'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'callout'; text: string }

export interface BlogArticle {
  slug: string
  titre: string
  metaTitle: string
  metaDescription: string
  datePublication: string // AAAA-MM-JJ
  extrait: string
  blocks: BlogBlock[]
}

export const articles: BlogArticle[] = [
  {
    slug: 'prix-location-autocar',
    titre: 'Combien coûte la location d\'un autocar avec chauffeur ? Tarifs 2026',
    metaTitle: 'Prix location autocar avec chauffeur 2026 : tarifs et exemples | Busmoov',
    metaDescription: 'Combien coûte un autocar avec chauffeur ? Fourchettes de prix 2026 : journée dès 690 € TTC, ce qui fait varier le tarif, exemples concrets et conseils pour payer moins cher.',
    datePublication: '2026-09-04',
    extrait: 'Journée dès 690 € TTC, transferts, séjours : les vraies fourchettes de prix d\'un autocar avec chauffeur, ce qui les fait varier et comment payer moins cher.',
    blocks: [
      { type: 'p', text: 'C\'est la première question de tous les organisateurs de groupe — et la réponse honnête est : ça dépend. Mais pas de n\'importe quoi. Le prix d\'un autocar avec chauffeur obéit à une logique simple une fois qu\'on la connaît. Voici les fourchettes réelles pratiquées en France en 2026 et les facteurs qui les font bouger.' },
      { type: 'h2', text: 'Les fourchettes de prix en un coup d\'œil' },
      { type: 'ul', items: [
        'Sortie à la journée en autocar standard (aller-retour local, jusqu\'à 59 places) : à partir de 690 € TTC',
        'Journée à forte amplitude (départ tôt, retour tard) : comptez plutôt 790 à 830 € TTC',
        'Transfert aller simple (aéroport, gare, événement) : souvent moins cher qu\'une journée complète, chiffré selon la distance et l\'horaire',
        'Minibus avec chauffeur (8 à 20 places) : environ 10 % de moins qu\'un autocar standard sur le même trajet',
        'Autocar grande capacité (60 à 90 places) : de 15 à 70 % de plus qu\'un standard selon la taille',
        'Séjour de plusieurs jours avec le car sur place : le tarif intègre les journées d\'immobilisation et l\'hébergement du chauffeur',
        'Longue distance : au-delà des trajets régionaux, le prix se calcule essentiellement au kilomètre',
      ]},
      { type: 'callout', text: 'Tous les prix du transport de voyageurs s\'entendent TTC avec une TVA à 10 % en France.' },
      { type: 'h2', text: 'Les 6 facteurs qui font varier le prix' },
      { type: 'p', text: '1. La distance, évidemment — mais par tranches : un trajet de 80 km et un trajet de 95 km peuvent coûter le même prix, car les transporteurs raisonnent en tranches kilométriques.' },
      { type: 'p', text: '2. L\'amplitude horaire du chauffeur : c\'est le temps entre son départ du dépôt et son retour, pas seulement votre temps de trajet. Un aller-retour avec 6 heures d\'attente sur place mobilise le chauffeur toute la journée. Au-delà de 12 heures d\'amplitude, la réglementation impose un second chauffeur, ce qui ajoute environ 500 € TTC au transfert.' },
      { type: 'p', text: '3. La taille du véhicule : un groupe de 65 personnes peut partir en un autocar grande capacité ou en deux véhicules — le devis compare souvent les deux options.' },
      { type: 'p', text: '4. La saison et le jour : les samedis de mai-juin (mariages), les samedis de vacances d\'hiver (stations de ski) et les périodes de voyages scolaires sont les créneaux les plus tendus. Les prix montent et les disponibilités fondent.' },
      { type: 'p', text: '5. La région de départ : la densité de transporteurs varie ; un départ depuis une grande métropole trouve plus facilement un car proche, donc sans frais d\'approche.' },
      { type: 'p', text: '6. La mise à disposition : si le car reste avec vous entre l\'aller et le retour (circuit, étapes multiples), on parle de mise à disposition — plus souple, mais plus cher qu\'un simple aller-retour.' },
      { type: 'h2', text: 'Trois exemples concrets' },
      { type: 'ul', items: [
        'Sortie CE Paris → Deauville à la journée, 50 personnes, autocar standard : de l\'ordre de 1 100 à 1 400 € TTC selon l\'amplitude',
        'Transfert mariage : navette de 3 rotations le soir entre la mairie et le domaine (20 km), minibus : environ 600 à 800 € TTC',
        'Classe de neige Lyon → Alpe d\'Huez, aller-retour à une semaine d\'intervalle, 53 élèves + accompagnateurs : environ 2 000 à 2 600 € TTC les deux trajets',
      ]},
      { type: 'p', text: 'Ces montants sont indicatifs : chaque devis dépend des disponibilités réelles des transporteurs au moment de la demande. C\'est précisément l\'intérêt de comparer plusieurs propositions.' },
      { type: 'h2', text: 'L\'acompte et le paiement' },
      { type: 'p', text: 'La règle du marché : un acompte de 30 % à la réservation, le solde avant le départ. Si le départ est à moins de 30 jours, l\'acompte passe généralement à 50 %, et à 100 % à moins de 15 jours. Le paiement se fait par carte ou virement.' },
      { type: 'h2', text: 'Comment payer moins cher : 5 leviers' },
      { type: 'ul', items: [
        'Réservez tôt : 6 à 8 semaines à l\'avance pour un trajet standard, 3 mois pour un samedi de haute saison',
        'Soyez flexible sur les horaires : réduire l\'amplitude du chauffeur (partir un peu plus tard, rentrer un peu plus tôt) peut faire changer de tranche tarifaire',
        'Évitez le samedi si votre événement le permet : le vendredi ou le dimanche sont souvent moins demandés',
        'Ajustez le véhicule au groupe réel : passer de 62 à 59 participants évite le surcoût grande capacité',
        'Comparez plusieurs transporteurs : sur un même trajet, l\'écart entre deux devis atteint couramment 15 à 25 % — c\'est exactement ce que Busmoov fait pour vous en une seule demande',
      ]},
      { type: 'h2', text: 'Obtenir un prix précis pour votre trajet' },
      { type: 'p', text: 'Décrivez votre trajet (départ, destination, date, horaires, nombre de passagers) dans notre formulaire : vous recevez sous 24 h plusieurs devis gratuits de transporteurs vérifiés, sans engagement. Le prix affiché est ferme et tout compris — carburant, péages et chauffeur inclus.' },
    ],
  },
  {
    slug: 'organiser-sortie-scolaire-autocar',
    titre: 'Organiser une sortie scolaire en autocar : le guide complet',
    metaTitle: 'Sortie scolaire en autocar : réglementation, prix, checklist | Busmoov',
    metaDescription: 'Réglementation transport d\'enfants, nombre d\'accompagnateurs, délais de réservation, budget et checklist : tout pour organiser une sortie scolaire en autocar sereinement.',
    datePublication: '2026-09-04',
    extrait: 'Réglementation, accompagnateurs, délais, budget : le guide pratique de l\'enseignant ou du parent d\'élève qui organise une sortie scolaire en autocar.',
    blocks: [
      { type: 'p', text: 'Musée, théâtre, classe verte, voyage de fin d\'année : la sortie scolaire commence toujours par la même question logistique — le transport. Voici ce qu\'il faut savoir pour organiser le trajet en autocar dans les règles, sans stress et sans mauvaise surprise budgétaire.' },
      { type: 'h2', text: 'La réglementation du transport d\'enfants' },
      { type: 'ul', items: [
        'Le véhicule doit être un autocar de transport en commun aux normes, équipé de ceintures de sécurité — obligatoires et à boucler pour tous les passagers',
        'Le pictogramme « transport d\'enfants » doit être apposé à l\'avant et à l\'arrière du véhicule',
        'Le transporteur doit être inscrit au registre des transporteurs de voyageurs (licence communautaire) — c\'est systématiquement vérifié chez les transporteurs du réseau Busmoov',
        'Chaque enfant compte pour une place assise : pas de surnombre, jamais',
        'Les trajets de nuit (entre minuit et 6 h) sont interdits pour les transports en commun d\'enfants, sauf dérogation',
      ]},
      { type: 'h2', text: 'Combien d\'accompagnateurs prévoir ?' },
      { type: 'p', text: 'L\'Éducation nationale fixe les taux d\'encadrement de la sortie elle-même : en élémentaire, 2 adultes minimum par classe, puis 1 adulte supplémentaire par tranche de 15 élèves au-delà de 30 (les seuils varient en maternelle et pour les sorties avec nuitée). Pensez à compter les accompagnateurs dans la capacité du car : une classe de 28 élèves avec 4 adultes occupe 32 places.' },
      { type: 'h2', text: 'Quel autocar pour quel effectif ?' },
      { type: 'ul', items: [
        'Jusqu\'à 20 personnes : minibus — pratique pour les petites sections ou les sorties de club',
        'De 21 à 59 personnes : autocar standard, le format le plus courant et le plus économique par personne',
        'De 60 à 90 personnes : autocar grande capacité ou double étage — ou deux cars standard, parfois plus simple pour les déposes',
        'Deux classes qui partent ensemble : deux véhicules coordonnés valent souvent mieux qu\'un très grand car complet',
      ]},
      { type: 'h2', text: 'Les délais : quand réserver ?' },
      { type: 'p', text: 'Pour une sortie à la journée en période creuse, 3 à 4 semaines suffisent. Mais les périodes de sorties scolaires sont les mêmes pour tout le monde : mai-juin et septembre-octobre saturent vite. Pour ces créneaux — et pour tout voyage avec nuitée — demandez vos devis 2 à 3 mois à l\'avance. Vous obtiendrez plus de choix et de meilleurs prix.' },
      { type: 'h2', text: 'Le budget' },
      { type: 'p', text: 'Une sortie à la journée en autocar standard démarre à 690 € TTC pour un trajet local — soit environ 12 à 15 € par élève pour une classe et demie. Le prix dépend surtout de la distance et de l\'amplitude horaire (l\'heure de départ du car et l\'heure de retour). Un départ à 9 h et un retour à 17 h coûtent moins cher qu\'une amplitude de 7 h à 20 h. Pour les trajets plus longs (classe découverte, voyage de fin d\'année), le devis se construit sur mesure.' },
      { type: 'callout', text: 'Astuce budget : mutualiser le car entre deux classes du même niveau divise presque par deux le coût de transport par élève.' },
      { type: 'h2', text: 'La checklist de l\'organisateur' },
      { type: 'ul', items: [
        'Liste nominative des passagers (élèves et adultes) — à conserver et à remettre au chauffeur en cas de contrôle',
        'Autorisations de sortie signées des parents',
        'Horaires validés avec le transporteur : heure de prise en charge, lieu exact de montée (attention aux zones de stationnement des cars devant l\'école), heure de retour',
        'Numéro de téléphone du chauffeur récupéré la veille du départ — Busmoov vous le transmet automatiquement',
        'Répartition des élèves et des adultes dans le car (un adulte près de chaque porte)',
        'Consignes données aux élèves : ceinture bouclée, on reste assis pendant le trajet',
        'Prévoir les sacs à l\'avance : les soutes se chargent avant la montée des enfants',
      ]},
      { type: 'h2', text: 'Les erreurs à éviter' },
      { type: 'ul', items: [
        'Sous-estimer l\'effectif : ajouter 3 accompagnateurs de dernière minute dans un car complet est impossible — prévoyez une marge dès le devis',
        'Oublier le temps de montée/descente : 50 enfants ne montent pas dans un car en 2 minutes ; intégrez 15 minutes de battement à chaque étape',
        'Réserver sur le seul critère du prix le plus bas sans vérifier le transporteur : licence, assurance et véhicule récent ne se négocient pas quand on transporte des enfants',
        'Attendre la dernière semaine pour confirmer : sans acompte versé, le car n\'est pas bloqué',
      ]},
      { type: 'h2', text: 'Demander un devis pour votre sortie scolaire' },
      { type: 'p', text: 'Indiquez la date, le trajet, l\'effectif (élèves + accompagnateurs) et vos horaires souhaités : vous recevez plusieurs devis gratuits sous 24 h de transporteurs habitués aux scolaires, véhicules aux normes transport d\'enfants. Écoles, collèges, lycées : le paiement par bon de commande administratif est possible.' },
    ],
  },
  {
    slug: 'difference-bus-autocar-minibus',
    titre: 'Bus, autocar, car, minibus : quelles différences ?',
    metaTitle: 'Différence entre bus, autocar, car et minibus | Busmoov',
    metaDescription: 'Bus, autocar, car, minibus : on dit tout et son contraire. Définitions, capacités, réglementation — et lequel louer pour votre groupe.',
    datePublication: '2026-09-04',
    extrait: 'On dit « bus » pour tout, mais le mot juste change la réservation. Définitions claires, capacités et lequel choisir pour votre groupe.',
    blocks: [
      { type: 'p', text: 'Vous voulez « louer un bus » pour un mariage, une sortie ou un séminaire ? Dans le langage courant, bus, car et autocar désignent la même chose. Mais côté réglementation et réservation, les mots ont un sens précis — et le connaître aide à demander le bon véhicule.' },
      { type: 'h2', text: 'Le bus : le véhicule urbain' },
      { type: 'p', text: 'Stricto sensu, le bus est un véhicule de transport urbain : lignes de ville, passagers debout autorisés, arrêts fréquents, pas de soute à bagages ni de ceintures. On ne loue pratiquement jamais un « vrai » bus pour un voyage privé — quand vous cherchez une « location de bus », c\'est en réalité un autocar qu\'il vous faut.' },
      { type: 'h2', text: 'L\'autocar (ou « car ») : le véhicule de voyage' },
      { type: 'p', text: 'L\'autocar est le véhicule de tourisme routier : sièges obligatoires pour tous, ceintures de sécurité, soutes à bagages, climatisation, et souvent Wi-Fi, prises USB et toilettes sur les modèles grand tourisme. « Car » n\'est que son abréviation courante. C\'est le véhicule de toutes les locations de groupe : excursions, mariages, voyages scolaires, transferts aéroport.' },
      { type: 'h2', text: 'Le minibus : le petit format' },
      { type: 'p', text: 'De 8 à 20 places, le minibus est l\'autocar des petits groupes : navettes VIP, comités de direction, rotations de fin de soirée. Au-delà de 9 places conducteur compris, sa conduite exige le permis D — c\'est pourquoi il se loue lui aussi avec chauffeur.' },
      { type: 'h2', text: 'Quelles capacités pour quel véhicule ?' },
      { type: 'ul', items: [
        'Minibus : 8 à 20 places — transferts, petits groupes, navettes',
        'Autocar standard : 21 à 59 places — le format le plus courant et le plus économique par personne',
        'Autocar grande capacité : 60 à 70 places — grands groupes en un seul véhicule',
        'Double étage : jusqu\'à 90 places — très grands événements',
      ]},
      { type: 'callout', text: 'Peu importe le mot que vous employez dans votre demande de devis : décrivez votre trajet et votre effectif, et le bon véhicule vous sera proposé. « Louer un bus pour 45 personnes » est parfaitement compris.' },
      { type: 'h2', text: 'Pourquoi toujours avec chauffeur ?' },
      { type: 'p', text: 'La conduite d\'un véhicule de plus de 9 places exige le permis D, une carte de qualification professionnelle (FIMO/FCO voyageurs) et le respect des temps de conduite réglementaires. La location d\'autocar est donc systématiquement une prestation avec chauffeur professionnel — carburant et péages inclus dans le prix.' },
    ],
  },
  {
    slug: 'location-autocar-mariage',
    titre: 'Location d\'autocar pour un mariage : navettes invités, prix et organisation',
    metaTitle: 'Autocar mariage : navettes invités, prix, organisation | Busmoov',
    metaDescription: 'Navettes de mariage en autocar ou minibus : combien ça coûte, comment organiser les rotations entre cérémonie, réception et hôtels, et les pièges à éviter.',
    datePublication: '2026-09-04',
    extrait: 'Le transport des invités est le détail logistique qui fait ou défait la soirée. Rotations, prix, timing : le guide complet des navettes de mariage.',
    blocks: [
      { type: 'p', text: 'Entre la mairie, l\'église, le domaine de réception et les hôtels des invités, un mariage est une petite opération logistique. La navette en autocar règle trois problèmes d\'un coup : personne ne se perd, personne ne conduit après le champagne, et le parking du domaine ne déborde pas.' },
      { type: 'h2', text: 'Le schéma classique des navettes' },
      { type: 'ul', items: [
        'Aller : prise en charge des invités à un ou deux points (hôtel, centre-ville) → cérémonie → réception',
        'Soirée : rotations de retour échelonnées (par exemple into 1h, 3h et fin de soirée) vers les hôtels',
        'Formule courante : un autocar pour le gros des invités + un minibus pour les derniers départs',
      ]},
      { type: 'p', text: 'Le véhicule reste généralement en mise à disposition : le chauffeur attend sur place et effectue les rotations à la demande. Précisez bien l\'heure de la dernière navette — c\'est elle qui détermine l\'amplitude du chauffeur, donc le prix.' },
      { type: 'h2', text: 'Combien ça coûte ?' },
      { type: 'p', text: 'Pour des navettes locales (moins de 30 km entre les sites), comptez à partir de 600 à 800 € TTC pour un minibus en soirée, et à partir de 690 € TTC pour un autocar standard à la journée. Une formule complète cérémonie + soirée avec retours tardifs se chiffre selon l\'amplitude — les retours après 2h du matin peuvent nécessiter un second chauffeur, intégré au devis dès le départ.' },
      { type: 'callout', text: 'Les samedis de mai à septembre sont les créneaux les plus demandés de l\'année : réservez votre navette 3 à 6 mois avant le mariage pour avoir le choix des transporteurs et des prix.' },
      { type: 'h2', text: 'Les 5 pièges à éviter' },
      { type: 'ul', items: [
        'Sous-estimer les horaires de fin : « on verra sur place » se paie en supplément — fixez la dernière rotation au devis',
        'Oublier l\'accès du domaine : certains châteaux ont des allées étroites, vérifiez que l\'autocar passe (sinon, minibus)',
        'Un seul point de prise en charge trop vague : donnez des adresses exactes et nommez un référent invité joignable',
        'Négliger le trajet retour des mariés : un minibus dédié en fin de soirée est un petit budget très apprécié',
        'Réserver au dernier moment : en haute saison, les transporteurs affichent complet des semaines à l\'avance',
      ]},
      { type: 'h2', text: 'Comment réserver' },
      { type: 'p', text: 'Décrivez votre journée (lieux, horaires estimés, nombre d\'invités transportés) dans le formulaire ci-dessous : vous recevez plusieurs devis gratuits sous 24h de transporteurs habitués aux mariages. Le nombre d\'invités en navette est souvent 60 à 70 % du total — tout le monde ne laisse pas sa voiture.' },
    ],
  },
  {
    slug: 'bus-soiree-etudiante-bde',
    titre: 'BDE : louer un bus pour une soirée étudiante ou un week-end d\'intégration',
    metaTitle: 'Location bus soirée étudiante et WEI : le guide du BDE | Busmoov',
    metaDescription: 'Location de bus pour BDE : soirées étudiantes, WEI, galas. Prix, sécurité, caution, retours de nuit — le guide pratique pour organiser le transport sans galère.',
    datePublication: '2026-09-04',
    extrait: 'Soirée, gala, WEI : le transport est la partie la plus sensible de l\'organisation. Prix, caution, retours de nuit — le guide pratique du BDE.',
    blocks: [
      { type: 'p', text: 'Pour un BDE, louer un bus n\'est pas un luxe : c\'est la seule façon d\'amener 50 étudiants à une soirée à 40 km du campus et de les ramener entiers. Voici comment organiser le transport d\'une soirée, d\'un gala ou d\'un week-end d\'intégration sans exploser le budget de l\'asso.' },
      { type: 'h2', text: 'Soirée ou gala : l\'aller-retour de nuit' },
      { type: 'p', text: 'Le format type : départ du campus vers 22h, dépose à la salle ou au club, le car revient chercher le groupe à l\'heure convenue (3h, 4h, 5h…). L\'heure de retour est LE paramètre du prix : elle détermine l\'amplitude du chauffeur. Un retour unique à heure fixe coûte bien moins cher que des rotations toute la nuit.' },
      { type: 'ul', items: [
        'Fixez une heure de retour ferme et communiquez-la aux participants — le car n\'attend pas les retardataires',
        'Prévoyez un responsable BDE sobre par véhicule, en lien avec le chauffeur',
        'Le nombre de places est strict : 53 inscrits dans un car de 53, pas un de plus',
      ]},
      { type: 'h2', text: 'Le WEI : plusieurs cars, un seul interlocuteur' },
      { type: 'p', text: 'Pour un week-end d\'intégration à 150 ou 300, il faut plusieurs autocars coordonnés : même heure de départ, convoi vers le lieu du WEI le vendredi, retour le dimanche. Demandez un devis global plutôt que car par car — et anticipez : les week-ends de septembre-octobre sont saturés dans toutes les villes étudiantes, réservez avant l\'été.' },
      { type: 'h2', text: 'Budget et caution' },
      { type: 'p', text: 'Un aller-retour de soirée local démarre autour de 690 € TTC en autocar standard — soit 12 à 14 € par participant sur un car plein, souvent répercutés sur le billet. Point important : l\'état du véhicule au retour engage l\'association. Un car rendu dégradé (sièges, vomi…) entraîne des frais de nettoyage ou de remise en état facturés. Briefez les participants : c\'est le budget de l\'asso qui trinque.' },
      { type: 'callout', text: 'Argument sécurité imparable auprès de l\'administration et des parents : avec un car, zéro voiture d\'étudiant sur la route de nuit. C\'est aussi ce qui rend la soirée assurable.' },
      { type: 'h2', text: 'Demander un devis pour votre événement' },
      { type: 'p', text: 'Indiquez le trajet, la date, l\'horaire de retour souhaité et l\'effectif : vous recevez plusieurs devis gratuits sous 24h. Association loi 1901 : la facture est établie au nom du BDE, paiement par virement possible.' },
    ],
  },
  {
    slug: 'transport-camp-scout-autocar',
    titre: 'Scouts : organiser le transport du camp en autocar',
    metaTitle: 'Transport de camp scout en autocar : guide et prix | Busmoov',
    metaDescription: 'Autocar pour camp scout : matériel en soute, réglementation transport de mineurs, budget serré, départs groupés — le guide pratique des chefs et responsables.',
    datePublication: '2026-09-04',
    extrait: 'Malles, tentes, budget serré et transport de mineurs : le guide pratique du responsable scout qui organise le départ en camp.',
    blocks: [
      { type: 'p', text: 'Chaque été, des milliers de jeunes partent en camp — et le transport est souvent le premier casse-tête du responsable de groupe : comment déplacer 40 jeunes, leurs sacs, les malles de matériel et les tentes, avec un budget d\'association ?' },
      { type: 'h2', text: 'Le matériel : la vraie question scout' },
      { type: 'p', text: 'Un camp, c\'est un volume de soute inhabituel : malles d\'intendance, tentes, pelles et outils, sacs de 60 litres. Un autocar standard offre 8 à 10 m³ de soute — suffisant pour un groupe de 40 avec matériel léger, juste pour un camp complet. Décrivez précisément le matériel dans la demande : le transporteur adapte le véhicule (soutes XXL) ou ajoute une remorque.' },
      { type: 'h2', text: 'Transport de mineurs : ce qui s\'applique' },
      { type: 'ul', items: [
        'Véhicule aux normes transport en commun d\'enfants : ceintures pour tous, pictogramme réglementaire',
        'Trajets de nuit interdits entre minuit et 6h pour les transports en commun de mineurs — planifiez des départs de jour',
        'Liste nominative des passagers à bord, encadrement conforme aux taux SGDF/SUF/EEDF de votre mouvement',
        'Une place assise par personne, matériel en soute uniquement (rien dans les allées)',
      ]},
      { type: 'h2', text: 'Maîtriser le budget' },
      { type: 'p', text: 'Le transport pèse lourd dans un budget de camp. Trois leviers : partir en semaine plutôt que le samedi (jusqu\'à 20 % d\'écart en juillet), mutualiser l\'autocar entre deux unités qui campent dans la même région, et réserver tôt — les demandes de devis de camps partent idéalement entre janvier et mars pour un départ en juillet. Un aller simple + un retour à deux semaines d\'intervalle se chiffrent comme deux transferts distincts.' },
      { type: 'callout', text: 'Astuce : pour les camps itinérants, l\'autocar peut assurer uniquement l\'approche (gare la plus proche → lieu de camp) en complément du train — souvent le meilleur rapport budget/empreinte carbone.' },
      { type: 'h2', text: 'Demander un devis pour votre camp' },
      { type: 'p', text: 'Précisez l\'effectif (jeunes + chefs), les dates aller et retour, le volume de matériel et les adresses exactes (les lieux de camp sont parfois au bout d\'un chemin — le transporteur vérifie l\'accessibilité). Devis gratuit sous 24h, facture au nom de l\'association.' },
    ],
  },
  {
    slug: 'autocar-deplacement-entreprise',
    titre: 'Déplacements d\'entreprise en autocar : séminaires, salons et transferts',
    metaTitle: 'Location autocar entreprise : séminaires, salons, transferts | Busmoov',
    metaDescription: 'Autocar avec chauffeur pour entreprises : séminaires, salons, transferts collaborateurs. Pourquoi le car s\'impose, combien ça coûte, comment ça se facture.',
    datePublication: '2026-09-04',
    extrait: 'Séminaire, salon, convention : déplacer 40 collaborateurs en autocar coûte moins cher que 15 notes de frais de taxi — et tout le monde arrive ensemble.',
    blocks: [
      { type: 'p', text: 'Un séminaire réussi commence dans le car. Faire voyager l\'équipe ensemble, c\'est arriver à l\'heure, ensemble, détendus — et c\'est souvent moins cher que l\'addition des notes de frais individuelles. Voici comment les entreprises utilisent l\'autocar avec chauffeur, et ce que ça coûte.' },
      { type: 'h2', text: 'Les cas d\'usage classiques' },
      { type: 'ul', items: [
        'Séminaire au vert : transfert bureau → lieu de séminaire, avec navettes activités sur place',
        'Salons et conventions : navette quotidienne hôtel ↔ parc des expositions pour l\'équipe',
        'Transfert gare ou aéroport pour une délégation ou des clients invités',
        'Soirée d\'entreprise : aller-retour avec retour tardif — personne ne reprend le volant',
        'Visites de sites industriels et voyages de récompense (incentive)',
      ]},
      { type: 'h2', text: 'L\'argument économique' },
      { type: 'p', text: 'Pour 40 collaborateurs sur 60 km, comparez : 10 voitures de location ou 13 taxis contre un seul autocar à partir de 690 € TTC la journée — soit environ 17 € par personne, péages, carburant et chauffeur inclus. Ajoutez l\'invisible : personne ne cherche de parking, personne n\'arrive en retard, et le trajet devient un temps d\'équipe (brief du matin, débrief du soir).' },
      { type: 'h2', text: 'Confort et image' },
      { type: 'p', text: 'Pour un déplacement client ou un comité de direction, le minibus grand confort (8-20 places, sièges cuir) fait le travail d\'une flotte de berlines avec chauffeur, à une fraction du prix. Pour les équipes, les autocars grand tourisme offrent Wi-Fi et prises USB — le trajet reste productif.' },
      { type: 'callout', text: 'Côté RSE : un autocar rempli émet environ 30 g de CO2 par passager-kilomètre, contre plus de 100 g en voiture individuelle. Un argument concret pour le bilan carbone des déplacements professionnels.' },
      { type: 'h2', text: 'Facturation et récurrence' },
      { type: 'p', text: 'Devis et facture au nom de l\'entreprise, paiement par virement, et pour les besoins récurrents (navette salon annuelle, séminaires trimestriels), un interlocuteur unique qui connaît vos habitudes. Décrivez votre déplacement dans le formulaire ci-dessous : plusieurs devis gratuits sous 24h.' },
    ],
  },
  {
    slug: 'bus-team-building',
    titre: 'Team building : privatiser un bus pour souder votre équipe',
    metaTitle: 'Location de bus pour team building : idées et organisation | Busmoov',
    metaDescription: 'Privatiser un bus pour un team building : destinations, organisation, budget — et pourquoi le trajet lui-même fait partie de l\'expérience d\'équipe.',
    datePublication: '2026-09-04',
    extrait: 'Le team building commence au moment où tout le monde monte dans le même véhicule. Destinations, formats et budget pour privatiser un bus d\'équipe.',
    blocks: [
      { type: 'p', text: 'Le secret d\'un team building réussi tient en une phrase : l\'équipe vit l\'expérience ensemble du début à la fin. Et ça commence au moment où tout le monde monte dans le même bus — pas éparpillés dans quinze voitures avec trois GPS différents.' },
      { type: 'h2', text: 'Le trajet fait partie de l\'événement' },
      { type: 'p', text: 'Un autocar privatisé, c\'est une salle commune roulante : quiz de lancement au micro du car, constitution des équipes pendant le trajet, playlists partagées, débrief au retour. Les organisateurs d\'événements le savent : l\'ambiance de la journée se joue dans la première heure — autant qu\'elle se joue ensemble.' },
      { type: 'h2', text: 'Les formats qui marchent' },
      { type: 'ul', items: [
        'Journée activité : escape game géant, olympiades, accrobranche — le car dépose, attend et ramène',
        'Rallye ou circuit à étapes : la formule mise à disposition permet d\'enchaîner les lieux (le car suit le groupe)',
        'Œnologie et gastronomie : visites de domaines avec dégustation — le chauffeur règle la question du retour',
        'Journée sportive : match, initiation surf ou ski selon la région — matériel en soute',
        'Soirée d\'équipe : restaurant + activité nocturne avec retour tardif au bureau ou aux hôtels',
      ]},
      { type: 'h2', text: 'Combien prévoir ?' },
      { type: 'p', text: 'Pour une équipe de 20 à 50 personnes, la journée en autocar standard démarre à 690 € TTC en local — dans un budget team building, le transport représente rarement plus de 15 %. Un minibus suffit pour les équipes de moins de 20. L\'amplitude (heure de départ, heure de retour) reste le principal curseur du prix.' },
      { type: 'callout', text: 'Conseil d\'organisateur : donnez un seul point de rendez-vous (le bureau) et une heure de départ ferme. La logistique disparaît pour les participants — c\'est exactement le but.' },
      { type: 'h2', text: 'Organiser votre team building' },
      { type: 'p', text: 'Indiquez la date, le lieu d\'activité (ou demandez conseil sur les destinations accessibles depuis votre ville), l\'effectif et les horaires : plusieurs devis gratuits sous 24h, facturation entreprise.' },
    ],
  },
  {
    slug: 'bus-discotheque-soiree',
    titre: 'Navette discothèque : louer un bus pour une soirée en boîte',
    metaTitle: 'Location bus discothèque : navette de soirée en toute sécurité | Busmoov',
    metaDescription: 'Louer un bus pour aller en discothèque : anniversaires, EVG/EVJF, groupes d\'amis. Prix d\'une navette de nuit, horaires de retour, sécurité — le guide.',
    datePublication: '2026-09-04',
    extrait: 'Anniversaire, EVG, soirée entre amis : la navette de nuit vers la discothèque, combien ça coûte et comment ça s\'organise.',
    blocks: [
      { type: 'p', text: 'Trente amis, une discothèque à 25 km, et la question qui fâche : qui ne boit pas ce soir ? La navette en bus ou minibus est la réponse des groupes organisés — anniversaires, EVG et EVJF, comités des fêtes — et elle coûte moins cher qu\'on ne le croit une fois divisée par le nombre de participants.' },
      { type: 'h2', text: 'Comment ça marche' },
      { type: 'p', text: 'Le format standard : prise en charge du groupe à un point unique en début de soirée, dépose devant l\'établissement, et retour à une heure convenue à l\'avance — le chauffeur revient vous chercher (formule aller-retour) ou reste sur place selon la durée. L\'heure de retour est le paramètre clé du prix : un retour à 2h coûte sensiblement moins cher qu\'un retour à 5h, qui allonge l\'amplitude de nuit du chauffeur.' },
      { type: 'h2', text: 'Combien ça coûte ?' },
      { type: 'ul', items: [
        'Minibus (jusqu\'à 20 personnes), soirée locale avec retour vers 2-3h : comptez de l\'ordre de 500 à 800 € TTC',
        'Autocar standard (jusqu\'à 59 personnes) : à partir de 690 € TTC selon distance et heure de retour',
        'Ramené par personne sur un véhicule plein : souvent 15 à 25 € — le prix de deux consommations',
      ]},
      { type: 'callout', text: 'Zéro voiture au parking de la boîte = zéro conducteur désigné, zéro contrôle au petit matin, zéro drame. C\'est l\'argument qui convainc tout le monde, parents des jeunes majeurs compris.' },
      { type: 'h2', text: 'Les règles du jeu' },
      { type: 'ul', items: [
        'Une heure de retour ferme, communiquée à tous : le bus n\'attend pas les retardataires au-delà du délai convenu',
        'Pas d\'alcool à bord : la consommation dans le véhicule est interdite — les festivités se passent à destination',
        'Un référent du groupe sobre, joignable par le chauffeur toute la soirée',
        'Le véhicule doit revenir propre : les dégradations et nettoyages exceptionnels sont facturés au client',
      ]},
      { type: 'h2', text: 'Réserver votre navette de soirée' },
      { type: 'p', text: 'Indiquez le point de départ, l\'établissement, la date et l\'heure de retour souhaitée : plusieurs devis gratuits sous 24h. Les samedis se réservent 2 à 3 semaines à l\'avance, davantage en période de fêtes.' },
    ],
  },
  {
    slug: 'autocar-bar-mitzvah',
    titre: 'Bar mitzvah : organiser les navettes des invités en autocar',
    metaTitle: 'Navettes bar mitzvah en autocar ou minibus | Busmoov',
    metaDescription: 'Transport des invités d\'une bar mitzvah ou bat mitzvah : navettes synagogue-réception, familles venues de loin, timing du chabbat — le guide d\'organisation.',
    datePublication: '2026-09-04',
    extrait: 'Synagogue, salle de réception, hôtels des familles : organiser les navettes d\'une bar mitzvah ou bat mitzvah sans stress.',
    blocks: [
      { type: 'p', text: 'Une bar mitzvah ou une bat mitzvah réunit souvent trois générations et des familles venues de loin — parfois de l\'étranger. Entre la synagogue, la salle de réception et les hôtels, la navette en autocar est ce qui permet aux invités de profiter de la fête sans se soucier des trajets ni du stationnement.' },
      { type: 'h2', text: 'Le schéma type des navettes' },
      { type: 'ul', items: [
        'Matin : prise en charge des invités aux hôtels ou à un point de rendez-vous → synagogue pour l\'office',
        'Midi ou soir : transfert synagogue → salle de réception (souvent le trajet où tout le monde doit arriver ensemble)',
        'Fin de fête : rotations de retour vers les hôtels — un minibus en complément gère les départs échelonnés',
      ]},
      { type: 'p', text: 'Pour une célébration le samedi, le timing s\'organise autour du chabbat : de nombreuses familles programment la réception le samedi soir après la sortie de chabbat, ou le dimanche. Précisez vos horaires exacts dans la demande — les navettes de fin de soirée déterminent l\'amplitude du chauffeur, donc le prix.' },
      { type: 'h2', text: 'Bien dimensionner' },
      { type: 'p', text: 'Comptez le nombre d\'invités qui utiliseront réellement la navette : les familles venues de loin (sans voiture sur place) et les aînés en priorité — souvent 50 à 70 % des convives. Un autocar de 59 places plus un minibus pour les rotations couvre la plupart des réceptions de 80 à 120 invités. Pour les groupes familiaux arrivant par avion ou train, un transfert aéroport/gare dédié la veille est courant.' },
      { type: 'callout', text: 'Astuce d\'organisation : indiquez sur le carton d\'invitation les points et horaires de navette. Les invités qui savent qu\'ils seront raccompagnés profitent de la fête jusqu\'au bout.' },
      { type: 'h2', text: 'Combien ça coûte ?' },
      { type: 'p', text: 'Des navettes locales (synagogue, salle et hôtels dans la même agglomération) démarrent autour de 600 à 800 € TTC en minibus et 690 € TTC et plus en autocar standard, selon l\'amplitude de la journée et les rotations de soirée. Décrivez votre programme dans le formulaire ci-dessous : plusieurs devis gratuits sous 24h, de transporteurs habitués aux réceptions familiales.' },
    ],
  },
]

export function getArticle(slug: string): BlogArticle | undefined {
  return articles.find((a) => a.slug === slug)
}
